spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-44-211-104-233.compute-1.amazonaws.com/dcru8nb3tv0f4d
  username: yynpgqdzuqepih
  password: 67f299f099ef81fda4c045bb4eb00b3863f29708265e9cf06a1dea2dcf66b1e5
  driver-class-name: org.postgresql.Driver

spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties:
    hibernate.format_sql: true
  show-sql: true

jwt:
  secret-key: fast_campus.sns-application-2022.secret_key
  # 30 days
  token.expired-time-ms: 2592000000
spring:
  sql:
    init:
      platform: postgres
  redis:
    url: redis://:pc80cf44dbd0d645a6f6ff45e45a8186441599f1480902e471d2e9ac52dc2931d@ec2-52-204-254-34.compute-1.amazonaws.com:9319